apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-server
  namespace: dop
spec:
  selector:
    matchLabels:
      app: monitoring-server
  replicas: 1
  template:
    metadata:
      labels:
        app: monitoring-server
    spec:
      containers:
        - name: monitoring-server
          imagePullPolicy: Always
          image: registry.dop.clsaa.com/dop/monitoring-server:<BUILD_TAG>
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
            - name: host-timezone
              mountPath: /etc/timezone
          ports:
            - containerPort: 14100
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: host-timezone
          hostPath:
            path: /etc/timezone
      nodeSelector:
        labelName: dop-node2
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-server
  namespace: dop
  labels:
    app: monitoring-server
spec:
  ports:
    - port: 14100
      protocol: TCP
      targetPort: 14100
  selector:
    app: monitoring-server
